version: '3'

services:
  redis:
    image: redis:5.0
    container_name: redis_container
    command: redis-server --requirepass testpass
    ports:
      - '6000:6379'

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: mysql_container
    ports:
      - 6001:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
  postgres:
    image: postgres:14
    container_name: postgres_container
    ports:
      - 6002:5432
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_container
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpass
    command: server --console-address ":9001" /data
    ports:
      - 6003:9000
      - 6004:9001

  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - 6005:4566 # all services
      - 6006:8080 # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # データのマウント
      - 'localstack-data:/tmp/localstack'
    environment:
      - SERVICES=s3,sqs,ses,cloudwatch,logs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
      - DISABLE_CORS_CHECKS=1
volumes:
  localstack-data:
    driver: 'local'
